indieapp/urls.py
from django.urls import path
from indieapp import views


app_name = 'cursor'

urlpatterns = [
    path('', views.fnt_inicio,name="inicio" ),
    path('detalle/<str:nombre>', views.fnt_detalle, name='detalle'),
    path('unity/', views.fnt_unity, name='unity'),
    path('rpgmaker/', views.fnt_rpgmaker, name='rpgmaker'),
    path('politicas/',views.fnt_politicas, name='politicas')
]

indieweb/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
#from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('indieapp.urls'))
]

# urlpatterns += [
#     re_path(r'^media/(?P<path>.*)$', serve,{
#         'document_root' : settings.MEDIA_ROOT,
#     })
# ]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

indieapp/models.py
from django.db import models
from django.db.models.fields import CharField, URLField, TextField
from django.db.models.fields.files import ImageField

# Create your models here.

class Tbl_motor(models.Model):
    nombre = CharField(max_length=100)

    def __str__(self):
        return self.nombre  

class Tbl_juegos(models.Model):
    nombre = CharField(max_length=100)
    sinopsis = TextField()
    img = ImageField(upload_to='indieapp/images/') 
    url_descargar = URLField(blank = True)
    fkidJuegos_idMotor = models.ForeignKey(Tbl_motor, null=True, blank=True, on_delete=models.CASCADE )
    
    def __str__(self):
        return (self.nombre + " - 290x501")


class Tbl_tres_populares(models.Model):
    fkidTrespopulares_idJuegos = models.ForeignKey(Tbl_juegos, null = True, blank = True, on_delete = models.PROTECT)
    img = ImageField(upload_to='indieapp/images/3_populares')
    posicion = CharField(max_length=25)

    def __str__(self):
        dimensiones = self.fnt_dimensiones(self.posicion)
        return f"{self.posicion} {dimensiones}"
    
    def fnt_dimensiones(self,posicion):
        self.dimensiones = {
            'inferior' : '680×230',
            'superior' : '680×230',
            'izquierda' : '680×430'
        }

        return self.dimensiones.get(posicion)

indieapp/views.py
from django.shortcuts import render,get_object_or_404
from .models import Tbl_juegos, Tbl_tres_populares
# from .models import Cls_juegos




# Create your views here.

def fnt_inicio(request):
    #consulta todos los elementos de la tabla juegos ordenados por el
    #último elemento agregado (-id) y que solo sean diez ([:10])
    carta_juego = Tbl_juegos.objects.all().order_by('-id')[:10]
    # img_populares = Tbl_tres_populares.objects.all()
    pos_izquierda = Tbl_tres_populares.objects.filter(posicion = 'izquierda').first()
    pos_superior = Tbl_tres_populares.objects.filter(posicion = 'superior').first()
    pos_inferior = Tbl_tres_populares.objects.filter(posicion = 'inferior').first()

    return render(request, 'indiewebapp/inicio.html', {'juegos' : carta_juego,
                                                        'izquierda' : pos_izquierda,
                                                        'superior': pos_superior,
                                                        'inferior': pos_inferior
                                                        })

def fnt_detalle(request, nombre):
    detalle_juego = get_object_or_404(Tbl_juegos, nombre=nombre)
  
    return render(request, 'indiewebapp/detalle.html', {'detalle_juego': detalle_juego})

def fnt_unity(request):

    #consulta los elementos dentro de la tabla juegos cuyo nombre sea (Unity)
    #para consultar el nombre de una llave fornea se debe enlazar la llave foranea con el nombre (__)
    carta_juego_unity = Tbl_juegos.objects.filter(fkidJuegos_idMotor__nombre = 'unity')

    return render(request,'indiewebapp/unity.html', {'juegos_unity' : carta_juego_unity} )

def fnt_rpgmaker(request):

    carta_juego_rpgmaker = Tbl_juegos.objects.filter(fkidJuegos_idMotor__nombre = 'rpgmaker')

    return render(request, 'indiewebapp/rpgmaker.html', {'juegos_rpgmaker' : carta_juego_rpgmaker})

def fnt_politicas(request):
    return render(request, 'indiewebapp/politicas.html')

indieapp/templates/indiewebapp/base.html
<!-- en Django para realizar los active links
se debe traer el nombre de las páginas  -->

{% url 'cursor:inicio' as inicio %}
{% url 'cursor:unity' as unity %}
{% url 'cursor:rpgmaker' as rpgmaker %}
{% url 'cursor:politicas' as politicas %}


<!DOCTYPE html>
<html lang="es">
<head>
    <!-- se carga la ruta donde están los elementos css, img, icons etc -->
    {%load static %}
    <!-- - -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Indie games</title>
    <link rel="stylesheet" href="{%static 'indiewebapp\css\reset.css' %}">
    <link rel="stylesheet" href="{% static 'indiewebapp/css/style_navbar.css' %}">
    <link rel="stylesheet" href="{% static 'indiewebapp/css/style_footer.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap">

</head>
<body>
    <!-- Aquí comienza la barra de navegación -->
    <header class="header">
        <a href="{% url 'cursor:inicio' %}">
        <div class="logo">
            <img src="{% static 'indiewebapp/img/indiegameslogo.jpg' %}" alt="indie logo">
        </a>
        </div>
        <div class="hamburger">
            <div class="line"></div>
            <div class="line"></div>
            <div class="line"></div>
        </div>
        <nav class="nav-bar">
            <ul class="nav-links">
                <li>
                    <!-- se debe crear una clase de tipo nav-link y un condicional 
                    el 'active' se puede personalizar en CSS -->
                    <a class="nav-link  {% if request.path == inicio %} active {% endif %}" href="{% url 'cursor:inicio' %}" >Inicio</a>
                </li>
                <li>
                    <a class="nav-link  {% if request.path == unity %} active {% endif %}" href="{% url 'cursor:unity' %}">Unity</a>
                </li>
                <li>
                    <a class="nav-link  {% if request.path == rpgmaker %} active {% endif %}" href="{% url 'cursor:rpgmaker' %}">RPGMaker</a>
                </li>
            </ul>
        </nav>
    </header>
    <!-- fin barra de navegación -->

    <!-- el contenido de esta zona cambia -->
    {% block content %}

    {% endblock %}
    <!-- fin de contenido cambiante -->


    <!-- Aquí comienza el pie de la página  -->
    <footer class="footer">
        <div class="container">
            <div class="footer-row">
                <div class="footer-links">
                    <h4>Indie games</h4>
                    <ul>
                        <li><a href="#">Patreon</a></li>
                        <li><a href="{% url 'cursor:politicas' %}">Políticas de Acceso y Descarga</a></li>
                    </ul>
                </div>
                <div class="footer-links">
                    <h4>Redes</h4>
                    <div class="social-links">
                        <a href="#"><i class="fab fa-twitter"></i></a>
                    </div>

                </div>
            </div>
        </div>

    </footer>
    <!-- fin del pie de página -->

<script src="{% static 'indiewebapp/js/script_navbar.js' %}"></script>

</body>
</html>

indieapp/templates/indiewebapp/detalle.html
{% extends "indiewebapp\base.html" %}
{% load static %}
{% block content %}

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">


<link rel="stylesheet" href="{%static 'indiewebapp\css\reset.css' %}">
<link rel="stylesheet" href="{%static 'indiewebapp\css\style_detalle.css' %}">

<main>
    <div class="container-detalle">
        <div class="box_img">
            <img src="{{detalle_juego.img.url}}" 
            alt="{{id.nombre}}">
        </div>
        <div class="box_info">
            <div class="container-text">
                <div class="box_name">
                    {{ detalle_juego.nombre }}
                </div>
                <div class="box_sinopsis">
                    <p>{{ detalle_juego.sinopsis}}</p>
                </div>
            </div>
            <div class="box_download">
                <a href="{{detalle_juego.url_descargar}}"  target="_blank">
                    <div class="btn_download">
                        Descargar
                        <img src="{% static 'indiewebapp/img/descargar.png' %}" 
                        alt="imagen-juego">
                    </div>
                </a>
            </div>  
        </div>
    </div>

</main>      

{% endblock %}

indieapp/templates/indiewebapp/inicio.html
{% extends "indiewebapp/base.html" %}
{% load static %}

{% block content %}

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
    rel="stylesheet">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">



<link rel="stylesheet" href="{%static 'indiewebapp\css\reset.css' %}">
<link rel="stylesheet" href="{% static 'indiewebapp/css/style_inicio.css' %}">

<section class="game_container">


    <!-- inicio tres populares -->
    <div class="container-fluid p-0 m-0">
        <div class="row g-2 align-items-stretch">

            <!-- Columna izquierda (imagen grande) -->
            <div class=" col-md-6 d-flex">
                <a href="{% url 'cursor:detalle' izquierda.fkidTrespopulares_idJuegos.nombre %}" class="w-100">
                    <div class="box-3-popular-1 card border-0 bg-transparent h-100">
                        <img src="{{ izquierda.img.url }}" class="card-img-top img-fluid h-100"
                            style="object-fit: cover;" alt="">
                    </div>
                </a>
            </div>

            <!-- Columna derecha (dos imágenes iguales en altura) -->
            <div class="col-md-6 d-flex flex-column gap-2">

                <!-- Imagen superior -->
                <a href="{% url 'cursor:detalle' superior.fkidTrespopulares_idJuegos.nombre %}" class="flex-fill">
                    <div class="box-3-popular-2 card border-0 bg-transparent h-100">
                        <img src="{{ superior.img.url }}" class="card-img-top img-fluid h-100"
                            style="object-fit: cover;" alt="">
                    </div>
                </a>

                <!-- Imagen inferior -->
                <a href="{% url 'cursor:detalle' inferior.fkidTrespopulares_idJuegos.nombre %}" class="flex-fill">
                    <div class="box-3-popular-3 card border-0 bg-transparent h-100">
                        <img src="{{ inferior.img.url }}" class="card-img-top img-fluid h-100"
                            style="object-fit: cover;" alt="">
                    </div>
                </a>

            </div>
        </div>
    </div>
    <!-- fin tres populares -->



    <div class="title-container-2">
        <h2 class="title">
            Novedades
        </h2>
        <small>
            Descubre los últimos juegos agregados.
        </small>
    </div>
    <!-- 'Juegos agregados recientemente' -->
    <div class="box-container-2">
        <!-- bucle for para mostrar el contenido de la base de datos -->
        {% for juego in juegos %}
        <a href="{% url 'cursor:detalle' juego.nombre %}">
            <div class="box">
                <div class="content">
                    <img src="{{ juego.img.url}}" alt="{{ juego.nombre }}">
                    <h3>{{juego.nombre}}</h3>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</section>




{% endblock %}

indieapp/templates/indiewebapp/politicas.html
{% extends "indiewebapp\base.html" %}
{% load static %}
{% block content %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
    rel="stylesheet">

<link rel="stylesheet" href="{%static 'indiewebapp\css\reset.css' %}">
<link rel="stylesheet" href="{% static 'indiewebapp\css\style_politicas.css' %}">
<main>
    <section class="welcome-section">
        <h2>Bienvenido a Indie games</h2>
        <p>Un espacio dedicado a la recopilación de juegos.</p>
    </section>
    <p>
    <section class="policies-section">
        <h3>Políticas de Acceso y Descarga</h3>
        <ul>
            <li>
                <strong>Naturaleza del Sitio:</strong>
                Este sitio web tiene un carácter meramente informativo y recopilatorio. La plataforma se limita a
                <strong>compartir enlaces externos a juegos disponibles en internet</strong>, sin almacenar ni
                distribuir directamente los archivos de los mismos.
            </li>

            <li>
                <strong>Responsabilidad sobre los Contenidos Externos:</strong>
                Todos los enlaces de descarga redirigen a sitios de terceros. Por lo tanto, no nos hacemos responsables
                de:
                <ul>
                    <li>• La disponibilidad, seguridad o legalidad de los archivos alojados en dichos sitios.</li>
                    <li>• Posibles daños, perjuicios o problemas técnicos derivados de la descarga o instalación de los
                        juegos enlazados.</li>
                </ul>
                El acceso y la descarga se realizan <strong>bajo exclusiva responsabilidad del usuario</strong>.
            </li>

            <li>
                <strong>Propiedad Intelectual del Sitio:</strong>
                El diseño, logotipos, textos, estructura, compilación y demás elementos propios de este sitio web son de
                uso exclusivo de la plataforma.
                <ul>
                    <li>• Queda <strong>prohibida la imitación, copia, reproducción o uso indebido</strong> de los
                        elementos propios de la web sin autorización previa y por escrito.</li>
                    <li>• El incumplimiento podrá dar lugar a las acciones legales correspondientes.</li>
                </ul>
            </li>

            <li>
                <strong>Uso Aceptable:</strong>
                El usuario se compromete a:
                <ul>
                    <li>• No utilizar este sitio con fines ilícitos o contrarios a la buena fe.</li>
                    <li>• Respetar en todo momento los derechos de autor de los desarrolladores y editores de los juegos
                        enlazados.</li>
                </ul>
            </li>

            <li>
                <strong>Limitación de Responsabilidad:</strong>
                El sitio no garantiza la disponibilidad ni el correcto funcionamiento de los enlaces externos en todo
                momento. Asimismo, se excluye cualquier responsabilidad por:
                <ul>
                    <li>• Descargas fallidas.</li>
                    <li>• Archivos corruptos o modificados por terceros.</li>
                    <li>• Consecuencias legales derivadas del uso inadecuado de los juegos enlazados.</li>
                </ul>
            </li>

            <li>
                <strong>Aceptación de las Políticas:</strong>
                El acceso y uso de esta web implica la <strong>aceptación plena de estas políticas</strong>. En caso de
                no estar de acuerdo, se recomienda abstenerse de utilizar la plataforma.
            </li>
    </section>
</main>


{% endblock %}

indieapp/templates/indiewebapp/rpgmaker.html
{% extends "indiewebapp/base.html" %}
{% load static %}

{% block content %}

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{%static 'indiewebapp\css\reset.css' %}">
<link rel="stylesheet" href="{% static 'indiewebapp/css/style_inicio.css' %}">


<div class="game_container">

    <div class="box-container-2">
        <!-- bucle for para mostrar el contenido de la base de datos -->
        {% for juego in juegos_rpgmaker %}
        <a href="{% url 'cursor:detalle' juego.nombre %}">
            <div class="box">
                <div class="content">
                    <img src="{{ juego.img.url}}" alt="{{ juego.nombre }}">
                    <h3>{{juego.nombre}}</h3>
                </div>
            </div>
        </a> 
        {% endfor %}    
    </div> 
    {% endblock %}
    </div>
    

indieapp/templates/indiewebapp/unity.html
{%extends "indiewebapp/base.html" %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{%static 'indiewebapp\css\reset.css'%}">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{%static 'indiewebapp\css\reset.css' %}">
<link rel="stylesheet" href="{% static 'indiewebapp/css/style_inicio.css' %}">



<div class="game_container">

<div class="box-container-2">
    <!-- bucle for para mostrar el contenido de la base de datos -->
    {% for juego in juegos_unity %}
    <a href="{% url 'cursor:detalle' juego.nombre %}">
        <div class="box">
            <div class="content">
                <img src="{{ juego.img.url}}" alt="{{ juego.nombre }}">
                <h3>{{juego.nombre}}</h3>
            </div>
        </div>
    </a> 
    {% endfor %}    
</div> 

{% endblock %}
</div>